version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "maintainers"
    assignees:
      - "maintainers"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "pip"
      include: "scope"
    ignore:
      - dependency-name: "spacy"
        versions: ["3.0.0", "3.1.0"]
      - dependency-name: "fastapi"
        versions: ["0.68.0", "0.68.1"] 